import { useEffect, useState } from 'react';
import Navbar from '../components/Navbar.jsx';
import Footer from '../components/Footer.jsx';
import PageHeader from '../components/PageHeader.jsx';
import { Icon } from '../components/Reveal.jsx';
import { intelligenceApi } from '../services/api.js';

// Small label that tells the user whether a panel is computed from their own
// saved data or generated by AI — so they can weigh the two differently.
function SourceTag({ kind }) {
  if (kind === 'ai') {
    return (
      <span className="badge bg-lime text-forest-800 shrink-0">
        <Icon name="sparkle" className="h-3.5 w-3.5" />
        AI suggestion
      </span>
    );
  }
  return (
    <span className="badge bg-forest-50 text-forest-700 border border-forest-100 shrink-0">
      <Icon name="chart" className="h-3.5 w-3.5" />
      Calculated
    </span>
  );
}

function SectionHeading({ icon, title, subtitle }) {
  return (
    <div className="flex items-start gap-3 mb-4">
      <span className="w-9 h-9 rounded-card bg-forest-50 text-forest-700 grid place-items-center shrink-0">
        <Icon name={icon} className="h-4 w-4" />
      </span>
      <div className="min-w-0">
        <h2 className="font-display text-lg font-semibold text-ink">{title}</h2>
        {subtitle && <p className="text-sm text-sage-600 mt-0.5">{subtitle}</p>}
      </div>
    </div>
  );
}

function Panel({ title, subtitle, tag, children }) {
  return (
    <section className="card p-5 sm:p-6">
      <div className="flex items-start justify-between gap-3 mb-4">
        <div className="min-w-0">
          <h3 className="font-semibold text-ink">{title}</h3>
          {subtitle && <p className="text-sm text-sage-600 mt-1">{subtitle}</p>}
        </div>
        {tag && <SourceTag kind={tag} />}
      </div>
      {children}
    </section>
  );
}

function Chips({ items = [] }) {
  if (!items.length) return <p className="text-sm text-sage-600">No data yet.</p>;
  return (
    <div className="flex flex-wrap gap-2">
      {items.map((item) => (
        <span key={String(item)} className="badge bg-forest-50 text-forest-700 border border-forest-100">
          {String(item)}
        </span>
      ))}
    </div>
  );
}

function ScoreBar({ label, score, note }) {
  // Distinguish a real value (including a genuine 0) from a missing one — never
  // render an unavailable score as 0%.
  const has = score !== null && score !== undefined && score !== '' && !Number.isNaN(Number(score));
  const value = has ? Math.max(0, Math.min(100, Number(score))) : 0;
  return (
    <div className="border border-border rounded-card p-3 bg-surface">
      <div className="flex justify-between gap-3 text-sm font-semibold text-ink">
        <span className="min-w-0">{label}</span>
        <span className={has ? 'shrink-0' : 'shrink-0 text-sage-500 font-normal'}>{has ? `${value}%` : 'Not enough data'}</span>
      </div>
      {has ? (
        <div className="h-2 bg-white rounded-full overflow-hidden mt-2">
          <div className="h-full bg-forest rounded-full transition-all duration-500" style={{ width: `${value}%` }} />
        </div>
      ) : (
        <div className="h-2 bg-white rounded-full overflow-hidden mt-2 border border-dashed border-border" />
      )}
      {note && <p className="text-xs text-sage-600 mt-2">{note}</p>}
    </div>
  );
}

function List({ items = [] }) {
  if (!items.length) return <p className="text-sm text-sage-600">No items yet.</p>;
  return (
    <div className="space-y-2">
      {items.map((item, index) => (
        <div key={`${item}-${index}`} className="flex gap-2 text-sm text-ink bg-surface border border-border rounded-card p-3">
          <Icon name="check" className="h-4 w-4 text-forest-700 shrink-0 mt-0.5" />
          <span>{String(item)}</span>
        </div>
      ))}
    </div>
  );
}

export default function CareerIntelligence() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [jobPost, setJobPost] = useState('');
  const [jobInspect, setJobInspect] = useState(null);
  const [checkingJob, setCheckingJob] = useState(false);

  useEffect(() => {
    let active = true;
    intelligenceApi.overview()
      .then((overview) => { if (active) setData(overview); })
      .catch((err) => { if (active) setError(err.message || 'Unable to load career intelligence.'); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);

  const inspectJob = async (e) => {
    e.preventDefault();
    if (!jobPost.trim()) return;
    setCheckingJob(true);
    try {
      setJobInspect(await intelligenceApi.inspectJob({ jobPost }));
    } catch (err) {
      setJobInspect({ scamRisk: 'Error', recommendation: err.message || 'Unable to inspect job post.', redFlags: [] });
    } finally {
      setCheckingJob(false);
    }
  };

  const vault = data?.careerVault;

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1 py-8 md:py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6">
          <PageHeader
            icon="chart"
            eyebrow="Career operating system"
            title="Career Intelligence Hub"
            subtitle="Dynamic insights from your profile, applications, generated content, roadmaps, job matches, and interviews."
          />

          {loading && (
            <div className="card p-6">
              <div className="flex items-center gap-3 text-sm text-sage-600">
                <span className="relative w-5 h-5 shrink-0">
                  <span className="absolute inset-0 rounded-full border-2 border-forest-100" />
                  <span className="absolute inset-0 rounded-full border-2 border-forest border-t-transparent animate-spin" />
                </span>
                Loading career intelligence...
              </div>
            </div>
          )}

          {!loading && error && (
            <div role="alert" className="card p-6 border-red-200 bg-red-50">
              <p className="flex items-center gap-2 font-semibold text-red-700"><Icon name="shield" className="h-4 w-4" />Could not load intelligence</p>
              <p className="text-sm text-red-700 mt-1">{error}</p>
              <p className="text-sm text-red-600/80 mt-1">This is a failed request, not an empty account. Reload the page to retry.</p>
            </div>
          )}

          {!loading && !error && data?.fallback && (
            <div className="card p-10 text-center">
              <div className="w-14 h-14 rounded-panel bg-forest-50 grid place-items-center mx-auto mb-4"><Icon name="chart" className="h-6 w-6 text-forest-700" /></div>
              <h3 className="font-semibold text-ink">Intelligence is not connected yet</h3>
              <p className="text-sm text-sage-600 mt-1 max-w-md mx-auto">Career intelligence needs its database connection to read your saved profile, interviews, applications, and generated content. No scores are shown because none could be calculated.</p>
            </div>
          )}

          {!loading && !error && data && !data.fallback && (
            <div className="space-y-10">
              {/* ── Overview ──────────────────────────────────────────── */}
              <div>
                <SectionHeading icon="chart" title="Overview" subtitle="Headline, calculated readiness signals across your workspace." />
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 mb-6">
                  {data.reportCards.map((card) => (
                    <ScoreBar key={card.label} label={card.label} score={card.score} note={card.note} />
                  ))}
                </div>
                <div className="grid grid-cols-1 lg:grid-cols-[1.1fr_0.9fr] gap-6">
                  <Panel title="Career Vault" subtitle="Your saved career memory used by the intelligence layer." tag="calculated">
                    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3 mb-4">
                      {Object.entries(vault.assets).map(([key, value]) => (
                        <div key={key} className="bg-surface border border-border rounded-card p-3">
                          <p className="text-xs text-sage-600 capitalize">{key.replace(/([A-Z])/g, ' $1')}</p>
                          <p className="text-2xl font-bold text-ink font-display">{value}</p>
                        </div>
                      ))}
                    </div>
                    <p className="text-sm text-sage-600 mb-3">Target role: <span className="font-semibold text-ink">{vault.targetRole}</span></p>
                    <Chips items={vault.savedSkills} />
                  </Panel>

                  <Panel title="Application Readiness" subtitle="Checks before applying to serious roles." tag="calculated">
                    <ScoreBar label="Readiness" score={data.applicationReadiness.score} />
                    <div className="mt-4 space-y-2">
                      {data.applicationReadiness.checks.map((check) => (
                        <div key={check.label} className="flex items-center justify-between gap-3 text-sm border border-border rounded-card p-2.5 bg-surface">
                          <span className="min-w-0">{check.label}</span>
                          <span className={`inline-flex items-center gap-1 font-semibold shrink-0 ${check.done ? 'text-forest-700' : 'text-amber-600'}`}>
                            <Icon name={check.done ? 'check' : 'history'} className="h-3.5 w-3.5" />
                            {check.done ? 'Done' : 'Pending'}
                          </span>
                        </div>
                      ))}
                    </div>
                  </Panel>
                </div>
              </div>

              {/* ── Applications ──────────────────────────────────────── */}
              <div>
                <SectionHeading icon="doc" title="Applications" subtitle="Calculated from your saved application pipeline." />
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  <Panel title="Application Analytics" subtitle="Response and offer rates from your pipeline." tag="calculated">
                    <ScoreBar label="Response rate" score={data.applicationAnalytics?.responseRate} />
                    <div className="mt-3"><ScoreBar label="Offer rate" score={data.applicationAnalytics?.offerRate} /></div>
                    <p className="text-sm text-sage-600 mt-3">Best source: <span className="font-semibold text-ink">{data.applicationAnalytics?.bestSource || 'Not enough data'}</span></p>
                    <p className="text-sm text-ink bg-surface border border-border rounded-card p-3 mt-3">{data.rejectionPattern}</p>
                  </Panel>

                  <Panel title="Resume Tailoring Diff" subtitle="Saved application resume before/after bullets." tag="calculated">
                    <div className="space-y-3">
                      {data.resumeTailoringDiff?.length ? data.resumeTailoringDiff.map((item) => (
                        <div key={`${item.companyName}-${item.role}`} className="bg-surface border border-border rounded-card p-3 min-w-0">
                          <p className="text-sm font-semibold text-ink">{item.companyName} - {item.role}</p>
                          <p className="text-xs text-sage-600 mt-2">Before: {item.before}</p>
                          <p className="text-xs text-sage-600 mt-1">After: {item.after}</p>
                          <div className="mt-2"><Chips items={item.addedKeywords} /></div>
                          <p className="text-xs text-forest-700 font-semibold mt-2">{item.atsImpact}</p>
                        </div>
                      )) : <p className="text-sm text-sage-600">Add resume before/after bullets in Application Tracker to see tailoring diffs.</p>}
                    </div>
                  </Panel>

                  <Panel title="Resume Proof Scores" subtitle="Project proof, metrics, stack, and outcome evidence." tag="calculated">
                    <div className="space-y-3">
                      {data.proofScores?.length ? data.proofScores.map((item) => (
                        <ScoreBar key={`${item.companyName}-${item.role}`} label={`${item.companyName} - ${item.role}`} score={item.score} />
                      )) : <p className="text-sm text-sage-600">Add applications to calculate proof scores.</p>}
                    </div>
                  </Panel>
                </div>

                <div className="grid grid-cols-1 mt-6">
                  <Panel title="Application Timeline" subtitle="Next actions from saved application records." tag="calculated">
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                      {data.applicationTimeline?.length ? data.applicationTimeline.map((item) => (
                        <div key={`${item.companyName}-${item.role}-${item.status}`} className="bg-surface border border-border rounded-card p-3 min-w-0">
                          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2 sm:gap-3">
                            <div className="min-w-0">
                              <p className="text-sm font-semibold text-ink">{item.companyName}</p>
                              <p className="text-xs text-sage-600">{item.role}</p>
                            </div>
                            <span className="badge bg-forest-50 text-forest-700 border border-forest-100 shrink-0">{item.status}</span>
                          </div>
                          <p className="text-xs text-sage-600 mt-2">Source: {item.source} | Priority: {item.priority}</p>
                          <p className="text-xs font-semibold text-ink mt-2">Next: {item.nextAction}</p>
                        </div>
                      )) : <p className="text-sm text-sage-600">No application timeline yet. Add applications to see upcoming actions.</p>}
                    </div>
                  </Panel>
                </div>
              </div>

              {/* ── Resume & skills evidence ──────────────────────────── */}
              <div>
                <SectionHeading icon="target" title="Resume & Skills Evidence" subtitle="Turn your profile and job analysis into stronger proof." />
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  <Panel title="ATS Resume Tailor" subtitle="Based on your latest job analysis." tag="ai">
                    <ScoreBar label="Latest match" score={data.atsTailor.latestMatchScore} />
                    <p className="text-xs font-semibold text-sage-600 uppercase tracking-wide mt-4 mb-2">Keywords to add</p>
                    <Chips items={data.atsTailor.keywordsToAdd} />
                    <p className="text-sm text-ink bg-surface border border-border rounded-card p-3 mt-4">{data.atsTailor.summarySuggestion}</p>
                  </Panel>

                  <Panel title="Skill Gap Projects" subtitle="Turn missing skills into proof projects." tag="ai">
                    <div className="space-y-3">
                      {data.skillGapProjects.length ? data.skillGapProjects.map((item) => (
                        <div key={item.skill} className="bg-surface border border-border rounded-card p-3">
                          <p className="font-semibold text-ink text-sm">{item.skill}</p>
                          <p className="text-sm text-sage-600 mt-1">{item.project}</p>
                          <p className="text-xs text-forest-700 font-semibold mt-2">{item.proof}</p>
                        </div>
                      )) : <p className="text-sm text-sage-600">Run Job Analyzer to discover skill-gap projects.</p>}
                    </div>
                  </Panel>

                  <Panel title="Portfolio Analyzer" subtitle="Keywords and improvements for your projects." tag="ai">
                    <Chips items={data.portfolioAnalyzer.projectKeywords} />
                    <div className="mt-4"><List items={data.portfolioAnalyzer.improvements} /></div>
                  </Panel>
                </div>
              </div>

              {/* ── Interview improvement ─────────────────────────────── */}
              <div>
                <SectionHeading icon="mic" title="Interview Improvement" subtitle="Practice signals from your saved interviews." />
                <div className="grid grid-cols-1 lg:grid-cols-[0.9fr_1.1fr] gap-6">
                  <Panel title="Voice Speech Analytics" subtitle="Computed from saved interview messages." tag="calculated">
                    {Object.entries(data.speechAnalytics).map(([key, value]) => (
                      <div key={key} className="flex justify-between gap-3 text-sm border-b border-border py-2 last:border-0">
                        <span className="text-sage-600 capitalize">{key.replace(/([A-Z])/g, ' $1')}</span>
                        <span className="font-semibold text-ink">{String(value)}</span>
                      </div>
                    ))}
                  </Panel>

                  <Panel title="Interview Moment Replay" subtitle="Review where points were gained or lost." tag="ai">
                    <div className="space-y-3">
                      {data.interviewReplay.length ? data.interviewReplay.map((item, index) => (
                        <div key={`${item.question}-${index}`} className="bg-surface border border-border rounded-card p-3">
                          <div className="flex items-start justify-between gap-3">
                            <p className="text-sm font-semibold text-ink min-w-0">{item.question}</p>
                            <span className="text-xs font-bold text-forest-700 shrink-0">{item.score}/10</span>
                          </div>
                          <p className="text-sm text-sage-600 mt-2">{item.feedback}</p>
                          <p className="text-xs text-ink mt-2">{item.betterAnswer}</p>
                        </div>
                      )) : <p className="text-sm text-sage-600">Complete interviews to unlock replay insights.</p>}
                    </div>
                  </Panel>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-6">
                  <Panel title="Behavioral Story Library" subtitle="Prompts to build your STAR stories." tag="ai">
                    <div className="space-y-3">
                      {data.behavioralStories.map((story) => (
                        <div key={story.type} className="bg-surface border border-border rounded-card p-3">
                          <p className="text-sm font-semibold text-ink">{story.type}</p>
                          <p className="text-sm text-sage-600 mt-1">{story.prompt}</p>
                        </div>
                      ))}
                    </div>
                  </Panel>

                  <Panel title="Weakness Practice Mode" subtitle="Targeted drills for weak spots." tag="ai">
                    <div className="space-y-3">
                      {data.weaknessPractice.map((item) => (
                        <div key={item.weakness} className="bg-surface border border-border rounded-card p-3">
                          <p className="text-sm font-semibold text-ink">{item.weakness}</p>
                          <p className="text-sm text-sage-600 mt-1">{item.drill}</p>
                        </div>
                      ))}
                    </div>
                  </Panel>
                </div>
              </div>

              {/* ── Job search & outreach ─────────────────────────────── */}
              <div>
                <SectionHeading icon="rocket" title="Job Search & Outreach" subtitle="Plans and scripts to move applications forward." />
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  <Panel title="Job Search Agent" subtitle="A daily plan toward your target role." tag="ai">
                    <p className="text-sm text-sage-600 mb-3">Target: <span className="font-semibold text-ink">{data.jobSearchAgent.targetRole}</span></p>
                    <Chips items={data.jobSearchAgent.searchQueries} />
                    <div className="mt-4"><List items={data.jobSearchAgent.dailyPlan} /></div>
                  </Panel>

                  <Panel title="Referral Finder" subtitle="Ways to reach insiders at your targets." tag="ai">
                    <List items={data.referralFinder.searchQueries} />
                    <p className="text-sm text-ink bg-surface border border-border rounded-card p-3 mt-3">{data.referralFinder.message}</p>
                    {data.referralFinder.contacts?.length ? (
                      <div className="mt-3 space-y-2">
                        {data.referralFinder.contacts.map((contact) => (
                          <div key={`${contact.companyName}-${contact.name}`} className="text-xs bg-surface border border-border rounded-card p-2 min-w-0">
                            <p className="font-semibold text-ink">{contact.name} - {contact.companyName}</p>
                            <p className="text-sage-600">{contact.email || contact.linkedIn || 'Contact saved'}</p>
                          </div>
                        ))}
                      </div>
                    ) : null}
                  </Panel>

                  <Panel title="Salary Coach" subtitle="Scripts and a negotiation checklist." tag="ai">
                    <List items={data.salaryCoach.scripts} />
                    <div className="mt-3"><Chips items={data.salaryCoach.negotiationChecklist} /></div>
                  </Panel>
                </div>

                <div className="grid grid-cols-1 mt-6">
                  <Panel title="Company Prep" subtitle="Generated from dream company and latest application data." tag="ai">
                    <p className="text-sm text-sage-600 mb-3">Company: <span className="font-semibold text-ink">{data.companyPrep.targetCompany}</span></p>
                    <List items={data.companyPrep.prepTasks} />
                  </Panel>
                </div>
              </div>

              {/* ── Job safety ────────────────────────────────────────── */}
              <div>
                <SectionHeading icon="shield" title="Job Safety" subtitle="Check any job post before you engage." />
                <Panel title="Job Red Flag Detector" subtitle="Paste any job post to detect scam signals and match fit." tag="ai">
                  <form onSubmit={inspectJob} className="space-y-3">
                    <label htmlFor="job-post" className="sr-only">Job post to inspect</label>
                    <textarea id="job-post" value={jobPost} onChange={(e) => setJobPost(e.target.value)} rows={7} className="form-textarea" placeholder="Paste job post, recruiter message, or job description..." />
                    <button className="btn-primary w-full" disabled={checkingJob}>{checkingJob ? 'Checking...' : 'Inspect Job Post'}</button>
                  </form>
                  {jobInspect && (
                    <div className="mt-4 bg-surface border border-border rounded-card p-4">
                      <p className="text-sm font-bold text-ink">Risk: {jobInspect.scamRisk}</p>
                      <p className="text-sm text-sage-600 mt-1">{jobInspect.recommendation}</p>
                      <div className="mt-3"><Chips items={jobInspect.redFlags || []} /></div>
                      {jobInspect.match && <div className="mt-4"><ScoreBar label="Profile match" score={jobInspect.match.score} /></div>}
                    </div>
                  )}
                </Panel>
              </div>

              {/* ── Career timeline ───────────────────────────────────── */}
              <div>
                <SectionHeading icon="history" title="Career Timeline" subtitle="Recent career activity across the whole platform." />
                <div className="card p-5 sm:p-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                    {data.careerTimeline.length ? data.careerTimeline.map((event) => (
                      <div key={`${event.type}-${event.title}-${event.date}`} className="bg-surface border border-border rounded-card p-3">
                        <p className="text-xs font-bold text-forest-700 uppercase tracking-wide">{event.type}</p>
                        <p className="text-sm font-semibold text-ink mt-1">{event.title}</p>
                        <p className="text-xs text-sage-600 mt-1">{event.date ? new Date(event.date).toLocaleString() : ''}</p>
                      </div>
                    )) : <p className="text-sm text-sage-600">No timeline activity yet.</p>}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
}
